import { Link } from "react-router-dom";
import SiteLayout from "@/components/SiteLayout";

const points = [
  { title: "Personally Reviewed Approvals", desc: "Every file is reviewed directly. Approval numbers are backed by data — not generated by a system." },
  { title: "No Inflated Numbers", desc: "Your client receives a purchase range grounded in reviewed financials. No surprises at the table." },
  { title: "Direct Communication", desc: "You will hear from me directly. Updates are timely, structured, and documented." },
  { title: "Accountability Through Closing", desc: "The process does not end at pre-approval. Structured execution continues through closing and beyond." },
  { title: "Preparation Before Offers", desc: "Your client will be positioned before offers are written — not scrambling to qualify after the fact." },
];

const Agents = () => (
  <SiteLayout>
    <section className="py-24 md:py-32 px-6 md:px-12">
      <div className="max-w-3xl mx-auto">
        <p className="font-mono text-xs text-primary tracking-widest uppercase mb-4">For Real Estate Agents</p>
        <h1 className="font-serif text-4xl md:text-6xl text-foreground leading-tight">
          Structured Files.<br />Stronger Contracts.
        </h1>
        <p className="mt-8 text-muted-foreground text-lg leading-relaxed max-w-2xl">
          When you work within The Standard, your clients are positioned — not just pre-approved.
          That distinction shows in negotiation, in closing timelines, and in client confidence.
        </p>
      </div>
    </section>

    <section className="bg-card py-24 md:py-32 px-6 md:px-12">
      <div className="max-w-3xl mx-auto space-y-10">
        {points.map((point, i) => (
          <div key={i}>
            <h3 className="font-serif text-xl text-foreground mb-2">{point.title}</h3>
            <p className="text-muted-foreground leading-relaxed">{point.desc}</p>
          </div>
        ))}
      </div>
    </section>

    <section className="py-24 md:py-32 px-6 md:px-12">
      <div className="max-w-3xl mx-auto">
        <Link
          to="/apply"
          className="inline-flex items-center justify-center bg-primary text-primary-foreground px-8 py-4 text-sm tracking-widest uppercase font-medium hover:opacity-90 transition-opacity"
        >
          Work Within The Standard
        </Link>
      </div>
    </section>
  </SiteLayout>
);

export default Agents;
