import SiteLayout from "@/components/SiteLayout";

const Intelligence = () => (
  <SiteLayout>
    <section className="py-24 md:py-32 px-6 md:px-12">
      <div className="max-w-3xl mx-auto">
        <p className="font-mono text-xs text-primary tracking-widest uppercase mb-4">Briefing 01</p>
        <h1 className="font-serif text-4xl md:text-6xl text-foreground leading-tight">
          Unfiltered Intelligence Briefing 01
        </h1>
        <p className="mt-6 text-muted-foreground text-lg">Market Patterns Inform Strategy.</p>
      </div>
    </section>

    <section className="bg-card py-24 md:py-32 px-6 md:px-12">
      <div className="max-w-3xl mx-auto">
        <article className="prose-custom space-y-6 text-muted-foreground leading-[1.85] text-[16px]">
          <p>
            There is a persistent belief among prospective buyers that interest rates should dictate the timing
            of a home purchase. This belief is reinforced daily by media cycles, social commentary, and
            well-intentioned but unstructured advice from peers. The result is a population of buyers who are
            perpetually waiting — waiting for a rate that feels comfortable, a market that feels settled, or a
            signal that feels certain enough to act upon.
          </p>
          <p>
            This briefing does not offer predictions. Predictions belong to forecasters with no accountability
            to your file. What this briefing offers is structure — a framework for evaluating how rate
            environments interact with your personal financial position.
          </p>

          <h3 className="font-serif text-foreground text-xl pt-4">The Rate Timing Fallacy</h3>
          <p>
            Buyers frequently cite "waiting for rates to drop" as their primary reason for delaying a purchase.
            The assumption is that a lower rate universally produces a better outcome. This is not consistently
            true. A lower rate in a compressed-inventory environment often correlates with increased competition,
            multiple-offer scenarios, and inflated purchase prices that offset the perceived savings of a rate
            reduction.
          </p>
          <p>
            The inverse is also worth examining. Higher rate environments tend to reduce competition, increase
            seller concessions, and create negotiation leverage that is structurally absent in low-rate markets.
            Buyers who position themselves during these windows — with proper financial preparation — often
            secure better contractual terms than those who wait for a rate headline they find acceptable.
          </p>

          <h3 className="font-serif text-foreground text-xl pt-4">The Missing Variable: Preparation</h3>
          <p>
            Rate is one variable. Preparation is the variable that is almost never discussed. A buyer who enters
            the market with a reviewed credit position, a documented income strategy, a clearly defined purchase
            range, and an aligned real estate agent operates from a fundamentally different position than a buyer
            who enters with a pre-qualification letter generated by a system and reviewed by no one.
          </p>
          <p>
            The distinction matters because the prepared buyer is not reactive. They are not making decisions
            based on urgency, emotion, or headlines. They are executing a strategy that has been defined in
            advance — a strategy that accounts for rate variability rather than being hostage to it.
          </p>

          <h3 className="font-serif text-foreground text-xl pt-4">Structured Positioning Over Market Timing</h3>
          <p>
            The position of this practice is clear: structured positioning outperforms market timing in every
            measurable outcome. Buyers who are positioned — financially, strategically, and psychologically —
            close more predictably, negotiate more effectively, and report higher confidence in their decisions.
          </p>
          <p>
            Buyers who wait for external conditions to align with internal readiness are, by definition, allowing
            external conditions to govern their largest financial decision. This is not strategy. This is
            reaction.
          </p>

          <h3 className="font-serif text-foreground text-xl pt-4">What This Means For Your File</h3>
          <p>
            If you are reading this briefing, you are likely evaluating whether now is the right time to act. The
            answer depends entirely on your preparation — not on a rate published this morning. If your financial
            position has not been reviewed by someone who will be accountable for the outcome, then the rate is
            irrelevant. You do not yet have the information required to make a structured decision.
          </p>
          <p>
            The first step is not a rate lock. The first step is a structured review.
          </p>
        </article>
      </div>
    </section>

    <section className="py-24 md:py-32 px-6 md:px-12">
      <div className="max-w-3xl mx-auto text-center">
        <h2 className="font-serif text-3xl text-foreground">Structure Your Position.</h2>
        <a
          href="https://scl.my1003app.com/554554/register"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center justify-center bg-primary text-primary-foreground px-8 py-4 text-sm tracking-widest uppercase font-medium mt-10 hover:opacity-90 transition-opacity"
        >
          Begin Structured Review
        </a>
      </div>
    </section>
  </SiteLayout>
);

export default Intelligence;
